### ISSUE TITLE
Changed name on Twitch but it didn't change on BF site

### ISSUE THREAD

**Issue by sergalbutt** [piercy/BeatFollowerPlugin#38]
I recently changed my username on Twitch and noticed the Twitch extension wouldn't load any information.
Logging directly into the BF website and it still came up with my old username. (I believe this is a similar/the same issue as #23 ) 

Giving the same information as the referenced issue, my current profile on BeatFollower is https://www.beatfollower.com/profile/Sparkz_AUS and my Twitch is http://twitch.tv/SPARKZicity

**Comment by piercy** [comment]
Hey, yeah profiles can take up to 24 hours to update.  I just forced yours to update a bit quicker (but it would have changed on its own in a few more hours).

Gonna close this as it does work, but i'm going to create a new ticket that will allow people to force the update.   Its a bit rubbish that it takes so long, so a force update button on the profile should help speed it along.

**Comment by sergalbutt** [comment]
Thanks!
