### ISSUE TITLE
deactivating your mod

### ISSUE THREAD

**Issue by austintexas65** [piercy/BeatFollowerPlugin#45]
I downloaded the mod thinking it was just a request mod, but when I played it it was different. Now I'm trying to delete it but it won't go away. Can someone explain how to actually get rid of it?

**Comment by piercy** [comment]
Hi @austintexas65 Yeah you want SongRequestManager for that.  This mod records you activity to a profile and allows you to easily create playlists to recommend to your viewers.

To remove the mod, if you go your BeatSaber folder, there should be a folder called plugins.   Inside this folder you should find BeatFollower.dll.  If you just delete that file, the mod will be removed.
